Kk 8182 plutus rails 7 upgrade
kopokopo/plutus pull request #1
Opened 2024-11-27 14:53 UTC by not-diba

2024-11-27 15:15 UTC, DavidKar1uk1 requested changes

2024-11-27 15:15 UTC, DavidKar1uk1 commented on plutus.gemspec
> +  s.required_ruby_version = ">= 3.3.6"
Can reduce this to 3.3.5 as core upgrade is running 3.3.5

2024-11-27 15:15 UTC, DavidKar1uk1 commented on plutus.gemspec
> +  s.homepage = %q{https://github.com/mbulat/plutus}
Shouldn't this be the kopo kopo plutus fork github page?

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/factories/account_factory.rb
>    factory :account, :class => Plutus::Account do |account|
With factorybot we do not need to do:
```ruby
factory :account, :class => Plutus::Account do |account|
```

It is enough to do:

```ruby
factory :account, class: Plutus::Account do
```

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/factories/account_factory.rb
>    factory :asset, :class => Plutus::Asset do |account|
Ditto

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/factories/account_factory.rb
>      account.name
Once we update to our current version of defining factories, we wont need to define the respective attributes as `account.name`. `name { Faker::Company.name }` is our current standard.

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/factories/amount_factory.rb
> +      amount { BigDecimal('473') }
Since `Plutus::DebitAmount` and `Plutus::CreditAmount` inherit from `Plutus::Amount`, no need to duplicate assign the `amount` and `association` attributes, provided they are nested within the following code block:
```ruby
factory :amount, class: 'Plutus::Amount' do

end
```

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/models/account_spec.rb
> +        expect(conflict).to be_invalid
Wrap in:

```ruby
aggregate_failures do
end
```

block if you have multiple expectations.

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/models/account_spec.rb
>          before {
Specify if `before(:each)` or `before(:all)`. By default `before` is for `before(:each)`, but we need to increase readability.

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/models/amount_spec.rb
>      it { should_not be_valid }  # construct a child class instead
Update from `should_not` to expectation rspec matchers

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/models/entry_spec.rb
> +      expect(entry).to be_invalid
Wrap in:

aggregate_failures do
end
block if you have multiple expectations.

2024-11-27 15:15 UTC, DavidKar1uk1 commented on spec/support/amount_shared_examples.rb
>    subject { amount }
No need to maintain subject as we can directly access amount from the let context

2024-11-28 12:32 UTC, DavidKar1uk1 approved these changes

2024-11-30 10:01 UTC, NicolletNjora approved these changes

2024-11-30 10:02 UTC, merged